### ISSUE TITLE
Firestore create mutation gives me "is not a valid Document" error

### ISSUE THREAD

**Issue by jonesnc** [Canner/gqlify#29]
**Describe the bug**
My GraphQL Schema looks like this with `FirebaseDataSource` set up.
```
type User @GQLifyModel(dataSource: "firestore", key: "users") {
  id: ID! @unique @autoGen # auto generate unique id
  username: String!
  email: String
}
```

Here's my `index.js` file:
```
const { Gqlify } = require('@gqlify/server');
const { ApolloServer } = require('apollo-server');
const { readFileSync } = require('fs');
const { FirestoreDataSource } = require('@gqlify/firestore');
const cert = require('./gqlify-firebase-adminsdk-a22pq-f37440b45b.json');
const databaseUrl = 'https://gqlify.firebaseio.com';

// Read datamodel
const sdl = readFileSync(__dirname + '/demo.graphql', { encoding: 'utf8' });

// construct gqlify
const gqlify = new Gqlify({
    sdl,

    dataSources: {
        firestore: args => new FirestoreDataSource(cert, databaseUrl, args.key)
    }
});

// GQLify will provide GraphQL apis & resolvers to apollo-server
const server = new ApolloServer(gqlify.createApolloConfig());

// start server
server.listen().then(({ url }) => {
    console.log(`🚀 Server ready at ${url}`);
});

```

When I try to run a `createUser` migration with:

```
mutation {
  createUser(
    data: {
      username: "newuser",
      email: "email@example.com"
    }) {
      id
    }
}
```

Gives me this error:

```
{
  "data": {
    "createUser": null
  },
  "errors": [
    {
      "message": "Argument \"data\" is not a valid Document. obj.hasOwnProperty is not a function",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createUser"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Argument \"data\" is not a valid Document. obj.hasOwnProperty is not a function",
            "    at Validator.(anonymous function).values [as isDocument] (/sandbox/node_modules/@google-cloud/firestore/build/src/validate.js:92:27)",
            "    at CollectionReference.add (/sandbox/node_modules/@google-cloud/firestore/build/src/reference.js:1680:25)",
            "    at FirestoreDataSource.<anonymous> (/sandbox/node_modules/@gqlify/firestore/lib/index.js:129:70)",
            "    at step (/sandbox/node_modules/@gqlify/firestore/lib/index.js:32:23)",
            "    at Object.next (/sandbox/node_modules/@gqlify/firestore/lib/index.js:13:53)",
            "    at /sandbox/node_modules/@gqlify/firestore/lib/index.js:7:71",
            "    at new Promise (<anonymous>)",
            "    at __awaiter (/sandbox/node_modules/@gqlify/firestore/lib/index.js:3:12)",
            "    at FirestoreDataSource.create (/sandbox/node_modules/@gqlify/firestore/lib/index.js:125:16)",
            "    at CreatePlugin.<anonymous> (/sandbox/node_modules/@gqlify/server/lib/plugins/create.js:137:55)"
          ]
        }
      }
    }
  ]
}
```

The `obj.hasOwnProperty is not a function` error may be due to graphql's usage of `Object.create(null)` when constructing `args`. See: https://github.com/graphql/express-graphql/issues/177#issuecomment-273955947

**To Reproduce**
1. Go to https://codesandbox.io/s/rrp9yjyoqn
2. Click on the `Execute Query` button in the GraphQL Playground window
3. See error

**Expected behavior**
A new `users` document to be created.

**Versions:**
```
"@gqlify/firestore": "^1.0.10",
"@gqlify/server": "^1.0.10",
"apollo-server": "^2.3.1"
```

**Comment by wwwy3y3** [comment]
hi @jonesnc should be fixed at version `v1.0.11`.

btw, you should move the firestore secret in your sandbox by using their secret key feature.
![screen shot 2018-12-23 at 3 51 16 pm](https://user-images.githubusercontent.com/1208829/50381793-adc46300-06ca-11e9-8e81-3d262906c64d.png)
