### ISSUE TITLE
TypeError: Cannot set property 'PageInfo' of undefined

### ISSUE THREAD

**Issue by yeuem1vannam** [Canner/gqlify#54]
**Describe the bug**
Cannot start the server because of RelayPlugin

**To Reproduce**
1. Create a fresh new app as the quick start
  ```bash
  mkdir gqlify-demo
  cd gqlify-demo
  yarn init -y
  yarn add @gqlify/server graphql apollo-server
  ```
2. Create `demo.graphql` and `index.js` file follow the quick start guide
3. Start the server by running `node index.js`
4. Error occurred
```text
Starting Gqlify...

  - Gqlify Models
    - Model User (generated from 'User')
    Field: id `ID!`
    Field: username `String!`
    Field: email `String`
    Field: books `[Book!]!` @relation(name: UserAndBookOnbooks)


    - Model Book (generated from 'Book')
    Field: id `ID!`
    Field: name `String!`
    Field: author `User!` @relation(name: UserAndBookOnbooks)


  - Relations
    Relation UserAndBookOnbooks
      * Type: Bidirectional One-to-Many
      * Relationship: 1-* on `User`-`Book`


/workspace/gqlify-demo/node_modules/@gqlify/server/lib/rootNode.js:247
        this.defBuilder._typeDefinitionsMap[name] = typeDefNode;
                                                  ^

TypeError: Cannot set property 'PageInfo' of undefined
    at RootNode.buildObjectType (/workspace/gqlify-demo/node_modules/@gqlify/server/lib/rootNode.js:247:51)
    at RootNode.addObjectType (/workspace/gqlify-demo/node_modules/@gqlify/server/lib/rootNode.js:93:23)
    at RelayPlugin.init (/workspace/gqlify-demo/node_modules/@gqlify/server/lib/plugins/relay.js:58:14)
    at /workspace/gqlify-demo/node_modules/@gqlify/server/lib/generator.js:22:24
    at Array.forEach (<anonymous>)
    at Generator.generate (/workspace/gqlify-demo/node_modules/@gqlify/server/lib/generator.js:17:22)
    at Gqlify.createServerConfig (/workspace/gqlify-demo/node_modules/@gqlify/server/lib/gqlify.js:107:34)
    at Gqlify.createApolloConfig (/workspace/gqlify-demo/node_modules/@gqlify/server/lib/gqlify.js:116:33)
    at Object.<anonymous> (/workspace/gqlify-demo/index.js:33:40)
    at Module._compile (module.js:653:30)
```

**Expected behavior**
Server start normally

**Screenshots**
- package.json
```json
{
  "name": "gqlify-demo",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@gqlify/server": "^3.2.1",
    "apollo-server": "^2.4.8",
    "graphql": "^14.2.1"
  }
}
```

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Docker image `node:8`
 - Version [e.g. 22] latest

**Additional context**

**Comment by yeuem1vannam** [comment]
It seems related to the version of `graphql` library.
After remove the `graphql` and downgrade the `@gqlify/server` to `v1.1.7`, the application can start successfully.
However, I cannot make it works for any version higher than 1.1.7

**Comment by aapav01** [comment]
I got the same issue

Use the Stable version v3.0.0 which was released 10 days ago it works fine

other versions are not stable...

and im using graphql@14.1.1

**Comment by alexandrethsilva** [comment]
Unfortunately I can't yet provide any meaningful solutions as I'm still trying to get my head around how GQLify works under the hood in an attempt to find fixes for other issues, but I hope this may point someone with more knowledge of the intent and purpose of the library internals in the right direction.

There has been an update on `ASTDefinitionBuilder` since `graphql-js@4.1.1` and some internal fields have been removed.

IMHO using `graphql-js` internals (as well as any other dependencies') should be probably reconsidered as it makes such issues impossible to avoid.

i.e. [this](https://github.com/graphql/graphql-js/blob/7fe9985eeb2237b7d47f560bf8f3a3f06a3c3ae2/src/utilities/buildASTSchema.js#L212):
```typescript
export class ASTDefinitionBuilder {
  _typeDefinitionsMap: TypeDefinitionsMap;
  _options: ?BuildSchemaOptions;
  _resolveType: TypeResolver;
  _cache: ObjMap<GraphQLNamedType>;

  constructor(
    typeDefinitionsMap: TypeDefinitionsMap,
    options: ?BuildSchemaOptions,
    resolveType: TypeResolver,
  ) {
    this._typeDefinitionsMap = typeDefinitionsMap;
    this._options = options;
    this._resolveType = resolveType;
    // Initialize to the GraphQL built in scalars and introspection types.
    this._cache = keyMap(
      specifiedScalarTypes.concat(introspectionTypes),
      type => type.name,
    );
  }

...

buildType(node: NamedTypeNode | TypeDefinitionNode): GraphQLNamedType {
    const typeName = node.name.value;
    if (!this._cache[typeName]) {
      if (node.kind === Kind.NAMED_TYPE) {
        const defNode = this._typeDefinitionsMap[typeName];
        this._cache[typeName] = defNode
          ? this._makeSchemaDef(defNode)
          : this._resolveType(node.name.value);
      } else {
        this._cache[typeName] = this._makeSchemaDef(node);
      }
    }
    return this._cache[typeName];
  }
```

became [this](https://github.com/graphql/graphql-js/blob/master/src/utilities/buildASTSchema.js#L214):
```typescript
export class ASTDefinitionBuilder {
  _options: ?BuildSchemaOptions;
  _resolveType: TypeResolver;

  constructor(options: ?BuildSchemaOptions, resolveType: TypeResolver) {
    this._options = options;
    this._resolveType = resolveType;
  }

...

buildType(astNode: TypeDefinitionNode): GraphQLNamedType {
    const name = astNode.name.value;
    if (stdTypeMap[name]) {
      return stdTypeMap[name];
    }

    switch (astNode.kind) {
      case Kind.OBJECT_TYPE_DEFINITION:
        return this._makeTypeDef(astNode);
      case Kind.INTERFACE_TYPE_DEFINITION:
        return this._makeInterfaceDef(astNode);
      case Kind.ENUM_TYPE_DEFINITION:
        return this._makeEnumDef(astNode);
      case Kind.UNION_TYPE_DEFINITION:
        return this._makeUnionDef(astNode);
      case Kind.SCALAR_TYPE_DEFINITION:
        return this._makeScalarDef(astNode);
      case Kind.INPUT_OBJECT_TYPE_DEFINITION:
        return this._makeInputObjectDef(astNode);
    }

    // Not reachable. All possible type definition nodes have been considered.
    /* istanbul ignore next */
    throw new Error(
      `Unexpected type definition node: "${inspect((astNode: empty))}".`,
    );
  }
...
```

My guess while having a first look is that this technique was being used to add the schema Types to this internal `_typeDefinitionsMap` of allowed definitions to be validated, but `graphql-js@4.2.1` uses a hard-coded list, coming from [this file](https://github.com/graphql/graphql-js/blob/master/src/type/scalars.js#L248), so... no dice.

```typescript
export const specifiedScalarTypes: $ReadOnlyArray<*> = [
  GraphQLString,
  GraphQLInt,
  GraphQLFloat,
  GraphQLBoolean,
  GraphQLID,
];
```

[This is the method](https://github.com/graphql/graphql-js/blob/master/src/utilities/buildASTSchema.js#L209) that checks against it:

```typescript
const stdTypeMap = keyMap(
  specifiedScalarTypes.concat(introspectionTypes),
  type => type.name,
);
```

@wwwy3y3 Does any of what I'm saying here make sense to you?

**Comment by nezaidu** [comment]
```
npm i graphql@14.1.0
``` 
helped me

**Comment by jthegedus** [comment]
Can confirm `graphql@14.3.1` does not work with `@gqlify/server@3.2.1` (both lastest at the time of writing). As @nezaidu said, installing `graphql@14.1.0` seems to resolve the issue at this time.
